{
  "$schema": "https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.5.json",
  "version": "2.1.0",
  "runs": [
    {
      "tool": {
        "driver": {
          "name": "CodeScanner",
          "semanticVersion": "2.1.0"
        }
      },
      "invocations": [
        {
          "commandLine": "CodeScanner @collections.rsp",
          "toolExecutionNotifications": [
            {
              "message": {
                "text": "Run started."
              },
              "level": "note",
              "descriptor": {
                "id": "CTN0001"
              }
            },
            {
              "message": {
                "text": "Exception evaluating rule \"C2152\". Rule disabled; run continues."
              },
              "level": "error",
              "threadId": 52,
              "timeUtc": "2016-07-16T14:18:43.119Z",
              "exception": {
                "kind": "ExecutionEngine.RuleFailureException",
                "message": "Unhandled exception during rule evaluation.",
                "innerExceptions": [
                  {
                    "kind": "System.ArgumentException",
                    "message": "length is < 0"
                  },
                  {
                    "kind": "System.CustomException",
                    "message": "Please look at innerexception for more details",
                    "innerExceptions": [
                      {
                        "kind": "System.ArgumentException",
                        "message": "length is < 0"
                      },
                      {
                        "kind": "CustomException",
                        "message": "Dig deeper!",
                        "innerExceptions": [
                          {
                            "kind": "Magic exception",
                            "message": "This is the true exception message."
                          }
                        ]
                      },
                      {
                        "kind": "AnotherCustomException",
                        "message": "This is make believe exception for testing."
                      }
                    ]
                  },
                  {
                    "kind": "YetAnotherCustomException",
                    "message": "This is make believe exception for testing."
                  }
                ]
              },
              "descriptor": {
                "id": "CTN9999"
              },
              "associatedRule": {
                "id": "C2152"
              }
            },
            {
              "message": {
                "text": "Run ended."
              },
              "level": "note",
              "descriptor": {
                "id": "CTN0002"
              }
            }
          ],
          "toolConfigurationNotifications": [
            {
              "message": {
                "text": "Could not disable rule \"ABC0001\" because there is no rule with that id."
              },
              "exception": {
                "kind": "ExecutionEngine.RuleFailureException",
                "message": "Unhandled exception during rule evaluation.",
                "innerExceptions": [
                  {
                    "kind": "ACustomException",
                    "message": "This is make believe exception for testing."
                  }
                ]
              },
              "descriptor": {
                "id": "UnknownRule"
              },
              "associatedRule": {
                "id": "ABC0001"
              }
            }
          ],
          "executionSuccessful": true
        }
      ],
      "columnKind": "utf16CodeUnits"
    }
  ]
}